name: egg_go
description: "Projeto para EggGo ltda."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  google_fonts: ^6.2.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  shared_preferences: ^2.2.2
  provider: ^6.1.5
  dio: ^5.4.3+1
  mask_input_formatter: ^0.0.3
  mask_text_input_formatter: ^2.9.0
  pdf: ^3.10.8
  printing: ^5.14.2
  intl: ^0.20.2
  sqflite: ^2.3.2
  path: ^1.9.0
  uuid: ^4.4.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - lib/core/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "core/images/app_icon.png"

flutter_native_splash:
  color: "#0xFFFFF6B6"
  image: core/images/logo.png
  android: true
  ios: true